### ISSUE TITLE
BUG: outputsInv and inputsInv in the .json's have too many entries

### ISSUE THREAD

**Issue by SimonBuxx** [SimonBuxx/LogiJS#13]
The inverted inputs/outputs arrays have far too many entries. This seems to be a new problem, but isn't effecting the functionality.

**Comment by SimonBuxx** [comment]
![unbenannt](https://user-images.githubusercontent.com/6598913/34064136-15e6abe0-e1f7-11e7-83e3-bfb671c5e1aa.JPG)
As an example, the 2-Bit counter has one input and two outputs but three inputs and six outputs are listed in the vector as not inverted.

**Comment by gatchrat** [comment]
![image](https://user-images.githubusercontent.com/28019767/34081949-21841a86-e356-11e7-876a-1e35c10f5734.png) works correctly for me. tested in chrome and edge

**Comment by SimonBuxx** [comment]
![unbenannt](https://user-images.githubusercontent.com/6598913/34082719-98023938-e363-11e7-8200-fb2cae85e94b.JPG)
Try loading the file "cpu" and immediatly save it and look under customs. All wrong for me in edge.

**Comment by gatchrat** [comment]
https://github.com/gatchrat/LogiJS/commit/ff75566aa7203f6deb173a2eadc2c04a2375d6e1 fixed.
Old save files even get fixed when loading  and saving them again.

**Comment by SimonBuxx** [comment]
Thank you! 

**This issue is now done with my last commit.**
