### ISSUE TITLE
TODO: Site title should only change if loaded file exists

### ISSUE THREAD

**Issue by SimonBuxx** [SimonBuxx/LogiJS#17]
The site title currently changes to whatever is typed into the input field when clicking load. There should be a check if the file exists before. Also, there should be an error message when a file doesn't exist.

**Comment by gatchrat** [comment]
https://github.com/gatchrat/LogiJS/commit/c7d9477a0d4422103f7533b06779a81416f9a4a4
though this may not be a good way to display the error

**Comment by crisbbi** [comment]
error shouldn't be displayed in the title bar because it would just cause confusion for the user. 
Instead show a notification/error window at the center of the screen or a subtle hint (overlapping the ui?) next to the text field.

**Comment by SimonBuxx** [comment]
Thank you, I added this with the last commit. Better error handling can be implemented in the future.
