### ISSUE TITLE
TODO : add Zooming into specific points

### ISSUE THREAD

**Issue by gatchrat** [SimonBuxx/LogiJS#2]
there should be a setting to turn this on and off

**Comment by SimonBuxx** [comment]
A.k.a "Geometric zoom". I tried this when implementing the zoom methods but it didn't really work out. Would be nice to have tough, but not a main priority right now.

**Comment by SimonBuxx** [comment]
We could do something like John Weisz in https://stackoverflow.com/questions/2916081/zoom-in-on-a-point-using-scale-and-translate. I tried to implement geometric zoom ages ago but it didn't work.

**Comment by SimonBuxx** [comment]
Relevant functions are mouseWheel() (mouse.js) and handleDragging() (sketch.js).

**Comment by SimonBuxx** [comment]
Done with the last commit, thanks to gatchrat.
