### ISSUE TITLE
TODO: Implement selecting

### ISSUE THREAD

**Issue by SimonBuxx** [SimonBuxx/LogiJS#22]
There's a button for selecting, but it currently has no functionality. Users should be able to select parts of the sketch to delete, copy or move them. Could be hard.

**Comment by SimonBuxx** [comment]
I'm on it. Objects can be selected by now, but not deselected at the moment. Replacing the selected objects (in the code) causes a few bugs with certain customs not working right. But moving and deleting will be implemented soon (hopefully). There could be smaller problems with copying, but nothing too bad. I'll tackle that when everything else about selection is done.

**Comment by gatchrat** [comment]
Is this comment up-to-date ? I think moving and deselecting works just fine

**Comment by SimonBuxx** [comment]
Moving is now implemented and also works with undo/redo. Closing this one after copy and delete are implemented

**Comment by gatchrat** [comment]
Delete is now implemented, only copy left

**Comment by SimonBuxx** [comment]
I'm working on selection-deleting wires, should be finished soon, incl. un/redo.

**Comment by SimonBuxx** [comment]
## Select Update

- Selection Moving is done, should be more stable than what we had years ago.
- Copy and Delete will follow, possibly harder to implement than moving.
- Marked elements have a new appearance (see image)

![image](https://user-images.githubusercontent.com/6598913/94688928-86360c00-032e-11eb-887b-8fc1e9f8d6de.png)

**Comment by SimonBuxx** [comment]
## Selection Delete is now implemented.

Hope it works out fine, didn't do too much testing yet.

Last thing is copy, got a lot to make out for that one, like maintaining unique IDs when copying objects, loading customs etc.
So don't expect that update to come tomorrow.

**Comment by SimonBuxx** [comment]
Copy feature is half-way done. I'll commit when everything is ready. At the moment, you can copy/paste sketch parts and undo pasting. Redo and bug testing is coming up next.

**Comment by SimonBuxx** [comment]
The copy feature is now live but in a beta-state. There are problems with undo/redo in some cases where elements get confused with each other or more undo/redo actions get logged than actually happened. I'll fix this asap. In the mean time, it's best to not use copy undo/redo.

**Comment by SimonBuxx** [comment]
Fixed an important copy undo/redo bug today. Didn't do too much bug testing though for copy. Anyway, I will now close this for now.
