### ISSUE TITLE
TODO: Undoing selection moving breaks when wires are changed after moving

### ISSUE THREAD

**Issue by SimonBuxx** [SimonBuxx/LogiJS#32]
Since today, moving the selected area can be undone and redone. The only known issue with this is that when you add or delete wire segments after moving, the wires won't move back when undoing adding/deleting and moving. This has to do with how the undo/redo algorithm works and I've no idea how to fix this at the moment. But I'll investigate and fix this as soon as possible with high priority.

**Comment by gatchrat** [comment]
should be fixed in my newest pull request

**Comment by SimonBuxx** [comment]
Fixed by gatchrat

**Comment by SimonBuxx** [comment]
This is broken again...

**Comment by SimonBuxx** [comment]
This works now, but moving bigger sketches now leads to random problems with some wire parts and conpoints...

**Comment by SimonBuxx** [comment]
This issue is now fixed but I had to mess with some things that lead to problems in wire delete und/redo. Will fix that soon.

**Comment by SimonBuxx** [comment]
Wire delete undo/redo works now.
