### ISSUE TITLE
TODO: Adapt GUI to support lower screen resolutions

### ISSUE THREAD

**Issue by SimonBuxx** [SimonBuxx/LogiJS#34]
At the moment, LogiJS is only optimized and tested for screens with 1080p and above. At lower resolutions, e.g. 720p, buttons in the GUI may overlap. To fix this, all button sizes should be relative to the resolution or the buttons could be layouted so that they fit in 720p. Also, button widths should be fixed and not determined by the font, like it is now. The canvas itself shouldn't have any issues with lower resolutions.

**Comment by SimonBuxx** [comment]
We're on it. Window height is now less of a problem because of the new scrolling feature. The elements in the top bar should be relayouted to fit into smaller screens.

**Comment by gatchrat** [comment]
The whole upper right side should be compressed into one button, which then gives acces to the the rest in a dropdown menu or something. 1 Action = 1 Button on Screen cant be sustained.

**Comment by SimonBuxx** [comment]
I moved to "Sync Ticks" checkbox to the bottom left and it's now only shown during simulation. This saves space in the top bar, but still not enough to not overlap on 1366x768p.

**Comment by SimonBuxx** [comment]
Since the last commit, the GUI fits in 1366x768p. This is sufficient for now, therefore I consider this as done. gatchrat's idea is now a seperate issue (#40).
